services:
  - type: web
    name: sof-umer
    env: node
    buildCommand: npm install && npm run build
    startCommand: node dist/server.js
    disk:
      name: data
      mountPath: /data
      sizeGB: 1
